ListaDeTarefas/Models/ErrorViewModel.cs
namespace ListaDeTarefas.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ListaDeTarefas/Models/TarefasModel.cs
namespace ListaDeTarefas.Models
{
    public class TarefasModel
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public string Status { get; set; }
    }
}

ListaDeTarefas/Controllers/HomeController.cs
using ListaDeTarefas.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ListaDeTarefas.Controllers
{
    public class HomeController : Controller
    {
        
        public IActionResult Index()
        {
            return View();
        }

    }
}

ListaDeTarefas/Controllers/TarefasController.cs
using ListaDeTarefas.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;


namespace ListaDeTarefas.Controllers
{
    public class TarefasController : Controller
    {
        private readonly string _caminhoArquivo;

        public TarefasController()
        {
            _caminhoArquivo = Path.Combine(Directory.GetCurrentDirectory(), "Models", "Dados", "tarefas.json");
        }
        public IActionResult Index(string filtro, string status)
        {
            var tarefas = ObterListaJson();
            if (!string.IsNullOrEmpty(filtro) || !string.IsNullOrEmpty(status))
            {
                tarefas = FiltrarTarefas(tarefas, filtro, status);
            }
            ViewBag.Tarefas = tarefas;
            ViewBag.Filtro = filtro;
            ViewBag.Status = status; 
            return View();
        }

        private List<TarefasModel> FiltrarTarefas(List<TarefasModel> tarefas, string filtro, string status)
        {
      
            if (string.IsNullOrEmpty(filtro) && string.IsNullOrEmpty(status))
            {
                return tarefas;
            }

            var tarefasFiltradas = tarefas.Where(t =>
                (string.IsNullOrEmpty(filtro) || t.Titulo.Contains(filtro) || t.Descricao.Contains(filtro)) &&
                (string.IsNullOrEmpty(status) || t.Status.Equals(status))
            ).ToList();

            return tarefasFiltradas;
        }

        [HttpGet]
        public IActionResult Criar(int id)
        {
            return View();
        }

        private int GerarNovoId(List<TarefasModel> tarefas)
        {
            if (tarefas.Count > 0)
            {
                return tarefas.Max(t => t.Id) + 1;
            }
            else
            {
                return 1;
            }
        }

        [HttpPost]
        public IActionResult Criar(TarefasModel novaTarefa)
        {
            if (ModelState.IsValid)
            {
                var listaTarefas = ObterListaJson();
                novaTarefa.Id = GerarNovoId(listaTarefas);
                listaTarefas.Add(novaTarefa);
                SalvarListaJson(listaTarefas);
                return RedirectToAction("Index");
            }
            return View(novaTarefa);
        }

        [HttpGet]
        public IActionResult Editar(int id)
        {
            var listaTarefas = ObterListaJson();
            var tarefa = listaTarefas.Where(w => w.Id == id).FirstOrDefault();
            ViewBag.TarefaEdit = tarefa;
            return View();
        }

        [HttpPost]
        public IActionResult Salvar(TarefasModel tarefaEditada)
        {
            
                var listaTarefas = ObterListaJson();
                var tarefaExistente = listaTarefas.FirstOrDefault(t => t.Id == tarefaEditada.Id);

                if (tarefaExistente != null)
                {
                    tarefaExistente.Titulo = tarefaEditada.Titulo;
                    tarefaExistente.Descricao = tarefaEditada.Descricao;
                    tarefaExistente.Status = tarefaEditada.Status;
                    SalvarListaJson(listaTarefas);

                    return RedirectToAction("Index");
                }
                else
                {
                    return NotFound();
                }
        }


        [HttpGet]
        public IActionResult Apagar(int id)
        {
            var tarefa = ObterTarefaPorId(id);
            if (tarefa == null)
            {
                return NotFound();
            }
            return View(tarefa);
        }

        [HttpGet]
        public IActionResult Visualizar(int id) 
        {
            var tarefa = ObterTarefaPorId(id);
            if (tarefa == null)
            {
                return NotFound();
            }
            return View(tarefa);
        }

        private TarefasModel ObterTarefaPorId(int id)
        {
            var listaTarefas = ObterListaJson();
            return listaTarefas.FirstOrDefault(t => t.Id == id);
        }

        [HttpPost]
        public IActionResult ConfirmarApagar(int id)
        {
            var listaTarefas = ObterListaJson();
            var tarefa = listaTarefas.FirstOrDefault(w => w.Id == id);

            if (tarefa != null)
            {
                listaTarefas.Remove(tarefa);
                SalvarListaJson(listaTarefas);
            }

            return RedirectToAction("Index");
        }

        private List<TarefasModel> ObterListaJson()
        {
            List<TarefasModel> tarefasModels;

            using (StreamReader sr = new StreamReader(_caminhoArquivo))
            {
                var json = sr.ReadToEnd();
                tarefasModels = JsonSerializer.Deserialize<List<TarefasModel>>(json);
            }

            return tarefasModels ?? new List<TarefasModel>();
        }

        private void SalvarListaJson(List<TarefasModel> lista)
        {
            using (StreamWriter sw = new StreamWriter(_caminhoArquivo))
            {
                var json = JsonSerializer.Serialize(lista);
                sw.Write(json);
            }
        }

       
     

    }
}

ListaDeTarefas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lista De Tarefas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ListaDeTarefas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Tarefas" asp-action="Index"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Tarefas" asp-action="Index">Tarefas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-dark">
        <div class="container">
            <a class="text-light">
            &copy; 2024 - Lista De Tarefas ASP .NET MVC RAZOR PAGES
            </a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ListaDeTarefas/Views/Tarefas/Apagar.cshtml
@model TarefasModel
@{
    ViewData["Title"] = "Apagar Tarefa";
}
<div style="text-align: center;">
<h2>Confirmação de exclusão</h2>
<br />
    <h5><p>Você deseja realmente excluir a tarefa:</p></h5>
<div class="card">
    
    <p><b>ID:</b>@Model.Id</p>
    <p><b>Título:</b>@Model.Titulo</p>
    <p><b>Descrição:</b>@Model.Descricao</p>
    <p><b>Status:</b>@Model.Status</p>
</div>
<br />
<div style="display: flex; justify-content-center">
    <div style="margin-right: 10px;">
        <form method="post">
            <input type="hidden" name="id" value="@Model.Id" />
            <button type="submit" class="btn btn-dark" formaction="@Url.Action("Index", "Tarefas")">Cancelar exclusão</button>
        </form>
    </div>
    <div>
        <form method="post" action="@Url.Action("ConfirmarApagar", "Tarefas")">
            <input type="hidden" name="id" value="@Model.Id" />
            <button type="submit" class="btn btn-danger">Confirmar exclusão</button>
        </form>
    </div>
</div>
</div>

ListaDeTarefas/Views/Tarefas/Criar.cshtml
@model TarefasModel
@{
    ViewData["Title"] = "Criar tarefas";
}
<div class="text-center">

    <h1 class="display-3">Cadastrar nova tarefa</h1>

    <br />
</div>
<form  asp-action="Criar">
    <div class="form-group">
        <label for="titulo">Titulo</label>
        <input class="form-control" placeholder="Insira o título da tarefa" id="titulo" name="Titulo" />
        
    </div>
    <br />
    <div class="form-group">
        <label for="descrição">Descrição</label>
        <input class="form-control" placeholder="Descreva a tarefa" type="text" id="descricao" name="Descricao" />
    </div>
    <br />
    <div class="form-group">
        <label for="status">Status</label>
        <select class="form-select" id="status" name="Status">
            <option selected>Selecione o satus</option>
            <option value="Aberto">Aberto</option>
            <option value="Em andamento">Em andamento</option>
            <option value="Concluido">Concluido</option>
        </select>
    </div>

    <br />
<button type="submit" class="btn btn-primary">Cadastrar</button>
<a class="btn btn-dark" asp-controller="Tarefas" asp-action="Index">Retornar ao menu</a>
</form>

ListaDeTarefas/Views/Tarefas/Editar.cshtml
@model TarefasModel
@{
    ViewData["Title"] = "Editar tarefas";
}
<div class="text-center">
    <h1 class="display-3">Editar tarefa</h1>
    <br />
</div>
<form method="post" asp-controller="Tarefas" asp-action="Salvar">
    <input type="hidden" name="Id" value="@ViewBag.TarefaEdit.Id" />
    <div class="form-group">
        <label for="titulo">Título</label>
        <input class="form-control" name="Titulo" aria-describedby="emailHelp" placeholder="Insira o título da tarefa" value="@ViewBag.TarefaEdit.Titulo">
    </div>
    <br />
    <div class="form-group">
        <label for="descricao">Descrição</label>
        <input class="form-control" name="Descricao" placeholder="" value="@ViewBag.TarefaEdit.Descricao">
    </div>
    <br />
    <div class="form-group">
        <label for="status">Status</label>
        <select class="form-select" name="Status">
            <option selected>Selecione o status</option>
            <option>Aberto</option>
            <option>Em andamento</option>
            <option>Concluído</option>
        </select>
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Salvar</button>
    <a class="btn btn-dark" asp-controller="Tarefas" asp-action="Index">Retornar ao menu</a>
</form>

ListaDeTarefas/Views/Tarefas/Index.cshtml
@model List<TarefasModel>
@{
    ViewData["Title"] = "Listagem de tarefas";
}

<div class="text-center">
    <h1 class="display-3">Listagem de Tarefas</h1>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Tarefas" asp-action="Criar">Nova tarefa</a>
    </div>
    <div class="mt-3">
        <form method="get" asp-controller="Tarefas" asp-action="Index">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Filtrar por título ou descrição" name="filtro" value="@ViewBag.Filtro">
                <select class="form-select" name="status">
                    <option value="">Todos os status</option>
                    <option value="Aberto">Aberto</option>
                    <option value="Em Progresso">Em Progresso</option>
                    <option value="Concluído">Concluído</option>
                </select>
                <button type="submit" class="btn btn-dark">Filtrar</button>
            </div>
        </form>
    </div>

</div>
<br />
<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Titulo</th>
            <th scope="col">Descrição</th>
            <th scope="col">Status</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody id="tarefas">
        @foreach (var item in ViewBag.Tarefas)
        {
            <tr>
                <th scope="row">@item.Id</th>
                <td>@item.Titulo</td>
                <td>@item.Descricao</td>
                <td>@item.Status</td>
                <td>
                    <div class="button" role="button">
                        <a role="button" class="btn btn-dark btn-block" href="@Url.Action("Visualizar", "Tarefas", new {id=item.Id})">Visualizar</a>
                        <a role="button" class="btn btn-success btn-block" href="@Url.Action("Editar", "Tarefas", new {id=item.Id})">Editar</a>
                        <a role="button" class="btn btn-danger btn-block" asp-controller="Tarefas" asp-action="Apagar" asp-route-id="@item.Id">Apagar</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

ListaDeTarefas/Views/Tarefas/Visualizar.cshtml
@model TarefasModel
@{
    ViewData["Title"] = "Visualizar Tarefa";
}
<div class="card" style="text-align: center;">
<p><b>ID:<b> @Model.Id</b></p>
<p><b>Titulo:</b> @Model.Titulo</p>
<p><b>Descrição:</b> @Model.Descricao</p>
<p><b>Status:</b> @Model.Status</p>
<br />
</div>
<br />
<a href="@Url.Action("Index", "Tarefas")" class="btn btn-dark">Voltar</a>